### ISSUE TITLE
How to compile and use it?

### ISSUE THREAD

**Issue by zieckey** [flier/zipkin-cpp#1]
Any documents?
Thanks.

**Comment by flier** [comment]
I'm still working on it, if you want to try, you could use [SCons](http://scons.org/).

**Comment by zieckey** [comment]
Thanks. 
Do you have any plans? roadmap?

**Comment by flier** [comment]
It should be completed and be used in some internal projects in a few week, then I may release a public beta version. 

Any way, you could try it with the example before the release, it should be works

**Comment by zieckey** [comment]
I would love to do it. Please give a step by step tutorial. Thanks.

**Comment by flier** [comment]
I'm working on it, please check the [Build](https://github.com/flier/zipkin-cpp/blob/develop/docs/Build.md) and [Getting Started](https://github.com/flier/zipkin-cpp/blob/develop/docs/GettingStarted.md) document, and give me your feedback, thanks

**Comment by zieckey** [comment]
Thanks very much.
Can you give an example of HTTP protocol instead of kafka?
Because the zipkin's example is HTTP, so any one can easily get started.

**Comment by flier** [comment]
Now, we use `CMake` to build the dependencies, please check the [Getting Started](https://github.com/flier/zipkin-cpp/blob/develop/docs/GettingStarted.md) guide for HTTP example.
