### ISSUE TITLE
build error

### ISSUE THREAD

**Issue by xiaoxiaolove** [flier/zipkin-cpp#10]
main.cpp:22:14: error: expected constructor, destructor, or type conversion before ‘(’ token
 DEFINE_string(logging, "", "Logging category configuration string");
              ^
main.cpp: In function ‘int main(int, char**)’:
main.cpp:40:24: error: ‘FLAGS_logging’ was not declared in this scope
   initLoggingGlogStyle(FLAGS_logging, LogLevel::INFO);
                        ^
Makefile:434: recipe for target 'main.o' failed
make[7]: *** [main.o] Error 1
Makefile:578: recipe for target 'all-recursive' failed
make[6]: *** [all-recursive] Error 1
Makefile:405: recipe for target 'all-recursive' failed
make[5]: *** [all-recursive] Error 1
Makefile:1910: recipe for target 'all-recursive' failed
make[4]: *** [all-recursive] Error 1
Makefile:1165: recipe for target 'all' failed
make[3]: *** [all] Error 2
CMakeFiles/Folly.dir/build.make:114: recipe for target 'externals/src/Folly-stamp/Folly-build' failed
make[2]: *** [externals/src/Folly-stamp/Folly-build] Error 2
CMakeFiles/Makefile2:68: recipe for target 'CMakeFiles/Folly.dir/all' failed
make[1]: *** [CMakeFiles/Folly.dir/all] Error 2
Makefile:138: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by flier** [comment]
seems you missed `gflags` library, could you paste the full build logs?

What's your OS and gcc version?

**Comment by xiaoxiaolove** [comment]
Thanks, @flier 

OS: Ubuntu 16.04.2 LTS
gcc:  version 5.4.0 20160609 (Ubuntu 5.4.0-6ubuntu1~16.04.4) 

But now, I have another error. Please see the detailed log.

========= detailed log =========
root@xiaoge:/usr/local/zipkin-cpp-0.3.1/build# make
[ 12%] Built target Folly
[ 25%] Built target GBench
[ 37%] Built target LibRDKafka
[ 50%] Built target RapidJSON
[ 62%] Built target Thrift
[ 84%] Built target zipkin
[ 86%] Building CXX object test/CMakeFiles/unittest.dir/TestTracer.cpp.o
In file included from /usr/local/include/gtest/gtest.h:58:0,
                 from /usr/local/include/gmock/internal/gmock-internal-utils.h:47,
                 from /usr/local/include/gmock/gmock-actions.h:46,
                 from /usr/local/include/gmock/gmock.h:58,
                 from /usr/local/zipkin-cpp-0.3.1/test/Mocks.hpp:3,
                 from /usr/local/zipkin-cpp-0.3.1/test/TestTracer.cpp:1:
/usr/local/zipkin-cpp-0.3.1/test/TestTracer.cpp: In member function ‘virtual void tracer_properties_Test::TestBody()’:
/usr/local/zipkin-cpp-0.3.1/test/TestTracer.cpp:7:5: **error**: no matching function for call to ‘testing::AssertionResult::AssertionResult(std::unique_ptr<zipkin::Tracer>&)’
     ASSERT_TRUE(tracer);
     ^
In file included from /usr/local/include/gmock/internal/gmock-internal-utils.h:47:0,
                 from /usr/local/include/gmock/gmock-actions.h:46,
                 from /usr/local/include/gmock/gmock.h:58,
                 from /usr/local/zipkin-cpp-0.3.1/test/Mocks.hpp:3,
                 from /usr/local/zipkin-cpp-0.3.1/test/TestTracer.cpp:1:
/usr/local/include/gtest/gtest.h:262:12: note: candidate: testing::AssertionResult::AssertionResult(bool)
   explicit AssertionResult(bool success) : success_(success) {}
            ^
/usr/local/include/gtest/gtest.h:262:12: note:   no known conversion for argument 1 from ‘std::unique_ptr<zipkin::Tracer>’ to ‘bool’
/usr/local/include/gtest/gtest.h:260:3: note: candidate: testing::AssertionResult::AssertionResult(const testing::AssertionResult&)
   AssertionResult(const AssertionResult& other);
   ^
/usr/local/include/gtest/gtest.h:260:3: note:   no known conversion for argument 1 from ‘std::unique_ptr<zipkin::Tracer>’ to ‘const testing::AssertionResult&’
In file included from /usr/local/include/gtest/gtest.h:58:0,
                 from /usr/local/include/gmock/internal/gmock-internal-utils.h:47,
                 from /usr/local/include/gmock/gmock-actions.h:46,
                 from /usr/local/include/gmock/gmock.h:58,
                 from /usr/local/zipkin-cpp-0.3.1/test/Mocks.hpp:3,
                 from /usr/local/zipkin-cpp-0.3.1/test/TestTracer.cpp:1:
/usr/local/zipkin-cpp-0.3.1/test/TestTracer.cpp: In member function ‘virtual void tracer_span_Test::TestBody()’:
/usr/local/zipkin-cpp-0.3.1/test/TestTracer.cpp:26:5: **error**: no matching function for call to ‘testing::AssertionResult::AssertionResult(std::unique_ptr<zipkin::Span>&)’
     ASSERT_TRUE(span);
     ^
In file included from /usr/local/include/gmock/internal/gmock-internal-utils.h:47:0,
                 from /usr/local/include/gmock/gmock-actions.h:46,
                 from /usr/local/include/gmock/gmock.h:58,
                 from /usr/local/zipkin-cpp-0.3.1/test/Mocks.hpp:3,
                 from /usr/local/zipkin-cpp-0.3.1/test/TestTracer.cpp:1:
/usr/local/include/gtest/gtest.h:262:12: note: candidate: testing::AssertionResult::AssertionResult(bool)
   explicit AssertionResult(bool success) : success_(success) {}
            ^
/usr/local/include/gtest/gtest.h:262:12: note:   no known conversion for argument 1 from ‘std::unique_ptr<zipkin::Span>’ to ‘bool’
/usr/local/include/gtest/gtest.h:260:3: note: candidate: testing::AssertionResult::AssertionResult(const testing::AssertionResult&)
   AssertionResult(const AssertionResult& other);
   ^
/usr/local/include/gtest/gtest.h:260:3: note:   no known conversion for argument 1 from ‘std::unique_ptr<zipkin::Span>’ to ‘const testing::AssertionResult&’
test/CMakeFiles/unittest.dir/build.make:134: recipe for target 'test/CMakeFiles/unittest.dir/TestTracer.cpp.o' failed
make[2]: *** [test/CMakeFiles/unittest.dir/TestTracer.cpp.o] Error 1
CMakeFiles/Makefile2:1239: recipe for target 'test/CMakeFiles/unittest.dir/all' failed
make[1]: *** [test/CMakeFiles/unittest.dir/all] Error 2
Makefile:138: recipe for target 'all' failed
make: *** [all] Error 2
root@xiaoge:/usr/local/zipkin-cpp-0.3.1/build#

**Comment by xiaoxiaolove** [comment]
The version of gmock and gtest in my computer is 1.7.0

**Comment by flier** [comment]
interesting, seems compile unit tests failed, let me build an environment to reproduce it

could  you try to use `gtest-1.8` with `-DUSE_BUNDLED_GTEST=on` argument in cmake command line.

**Comment by flier** [comment]
Could you give your `cmake` output? It seems you install gtest/gmock with `apt-get`?

**Comment by xiaoxiaolove** [comment]
I am sorry, I am not a c++ developer. I would like to use zipkin-cpp to extend nginx module. But so far, I have not built success. Always fail to build the test module on ubuntu 16.04. But, I have no idear for folly build on centos 6.9. Can you give me a detailed guidance. Thanks a lot.

**Comment by xiaoxiaolove** [comment]
I have built success on ubuntu 16.04. Because my product environment is on centos. So I build on centos 7.1611. But, I have an error
==================
./generate_fingerprint_tables: symbol lookup error: ./generate_fingerprint_tables: undefined symbol:_ZN6google14FlagRegistererC1IiEEPKcS3_S3_PT_S5_
make[5]: *** [FingerprintTables.cpp] Error 127
make[4]: *** [all-recursive] Error 1
make[3]: *** [all] Error 2
make[2]: *** [externals/src/Folly-stamp/Folly-build] Error 2
make[1]: *** [CMakeFiles/Folly.dir/all] Error 2
make: *** [all] Error 2
==================
Can you help me. Thank you very much.

Precondition: 
# sudo yum install autoconf libtool libevent-devel boost-devel libcurl-devel double-conversion-devel thrift-devel gflags-devel glog-devel

os: centos 7.1611
gcc: 5.4.0
gflags: 2.2.1
glog: 0.3.5
cmake: 3.8.2
curl: 7.54.1
jemalloc: 5.0.1

**Comment by flier** [comment]
It seems you link to wrong `google-flags` library which missed `ZN6google14FlagRegistererC1IiEEPKcS3_S3_PT_S5` symbol.

It is usual occurred when you install two different version of library, compile with newer include files, link with older library files.

You may consider to remove the system `gflags` library, or force to user bundled `cflags` library with `-DUSE_BUNDLED_GFLAGS=on` argument for cmake.

**Comment by xiaoxiaolove** [comment]
Thank God, according to the feature/docker-build branch, I have built success on centos-7.1611. How should I write a separate example that will be built use the library of zipkin-c++. I want to send trace data to zipkin over HTTP. Can you give me a demo. Thank you very much.

**Comment by flier** [comment]
👍 

You can check with the [C++ gRPC example](https://github.com/flier/zipkin-cpp/blob/master/examples/grpc_greeter/greeter_client.cc#L127) or [C example](https://github.com/flier/zipkin-cpp/blob/master/examples/simple_proxy/main.c#L527), the `Collector` should [created base on your scheme](https://github.com/flier/zipkin-cpp/blob/master/src/Collector.cpp#L118).

**Comment by xiaoxiaolove** [comment]
I write a simple demo, but no succeed.

*** Error in `./demo': double free or corruption (fasttop): 0x000000000091bf00 ***
======= Backtrace: =========
/lib64/libc.so.6(+0x7c503)[0x7f618c942503]
./demo(_ZNSt10unique_ptrIN6zipkin8HttpConfESt14default_deleteIS1_EED1Ev+0x5a)[0x47345a]
./demo(main+0x1c3)[0x470cc3]
/lib64/libc.so.6(__libc_start_main+0xf5)[0x7f618c8e7b35]
./demo[0x472a95]
======= Memory map: ========
00400000-005ed000 r-xp 00000000 fd:00 34991650                           /usr/local/tools/zipkin-cpp/build/examples/demo/demo
...

#include <iostream>
#include <memory>
#include <string>

#include <gflags/gflags.h>
#include <glog/logging.h>

#include <folly/Format.h>
#include <folly/String.h>
#include <folly/Uri.h>

#include <zipkin/zipkin.hpp>

class Hello
{
    public:
        Hello(std::shared_ptr<zipkin::Collector> collector)
            : tracer_(zipkin::Tracer::create(collector.get()))
        {
        }

        std::string hello(const std::string &user)
        {
            zipkin::Span &span = *tracer_->span("SayHello");

            struct curl_slist *headers;
            zipkin::Propagation::inject(headers, span);

            zipkin::Endpoint endpoint("hello client");

            span << std::make_pair("name", user) << endpoint
                 << zipkin::TraceKeys::CLIENT_SEND << endpoint;

            span << zipkin::TraceKeys::CLIENT_RECV << endpoint;

            return "OK";
        }

    private:
        std::unique_ptr<zipkin::Tracer> tracer_;
};
int main(int argc, char **argv) {
    google::InitGoogleLogging("11111111");

    std::unique_ptr<zipkin::HttpConf> conf(new zipkin::HttpConf("http://localhost:9411/api/v1/spans"));
    std::shared_ptr<zipkin::HttpCollector> collector(conf->create());

    Hello hello(collector);
    std::string user("你好");
    std::string ret = hello.hello(user);
    std::cout << "结果：" << ret << std::endl;

    //if (collector.get()) {
    //    collector->shutdown(std::chrono::seconds(5));
    //}

    google::ShutdownGoogleLogging();

    return 0;
}
