### ISSUE TITLE
Always failed HTTP status 202

### ISSUE THREAD

**Issue by xiaoxiaolove** [flier/zipkin-cpp#16]
I0921 17:17:27.470974 69448 Collector.cpp:224] HTTP collector started
I0921 17:17:27.471639 69448 HttpCollector.cpp:230] sending HTTP request to http://localhost:9411/api/v1/spans
I0921 17:17:27.505244 69448 HttpCollector.cpp:259] HTTP request finished, status 202, uploaded 121 bytes in 0.033454 seconds (3.53125 KB/s)

I have developed a nginx module to trace requests. But always have this above error. Now, I write a simple in the directory "zipkin-cpp/example/demo". But same error. Can you help me

#include <stdio.h>
#include <string.h>
#include "zipkin.h"

int main(int argc, char **argv)
{
    zipkin_collector_t collector = zipkin_collector_new("http://localhost:9411/api/v1/spans");
    if (!collector) {
        return -2;
    }
    zipkin_tracer_t tracer = zipkin_tracer_new(collector);
    if (!tracer) {
        return -3;
    }

    zipkin_span_t span = zipkin_span_new(tracer, "demo", NULL);
    ANNOTATE(span, ZIPKIN_SERVER_RECV, NULL);
    ANNOTATE(span, ZIPKIN_SERVER_SEND, NULL);

    zipkin_span_submit(span);

    if (collector) {
        zipkin_collector_shutdown(collector, 2000);
        free(zipkin_tracer_userdata(tracer));
        zipkin_tracer_free(tracer);
        zipkin_collector_free(collector);
    }
}

**Comment by nicksbyman** [comment]
Hi xiaoxiaolove, what is the error? Is 202 not an acceptable status code for your needs? Or are your negative return values hit in your test program?

**Comment by xiaoxiaolove** [comment]
I am sorry. It's not an error. Because I forgot to add an endpoint, so I don't search a tracing. I have fixed this issue. Thanks a lot.
