### ISSUE TITLE
BaseCollector doesn't destruct properly.

### ISSUE THREAD

**Issue by rnburn** [flier/zipkin-cpp#5]
Something like 
```cpp
#include <zipkin/zipkin.hpp>

int main() {
  std::shared_ptr<zipkin::Collector> collector;
  collector.reset(zipkin::Collector::create("http://localhost:9411"));
  return 0;
}
```
will exit via std::terminate. I expect it's because the m_worker thread started from BaseCollector isn't joined upon destruction.

**Comment by flier** [comment]
It hard to graceful shutdown collector in it's destructor, I prefer to use `Collector::shutdown` explicit
 .
```c++
#include <zipkin/zipkin.hpp>

int main() {
  std::shared_ptr<zipkin::Collector> collector;
  collector.reset(zipkin::Collector::create("http://localhost:9411"));
  collector->shutdown(std::chrono::milliseconds(500));
  return 0;
}
```
Another option is to return a wrapper like `CollectorGuard` from `Collector::create`, which shutdown the collector when it was destroyed, but it need introduce a redundant smart pointer.

At least, we could force to detach the worker thread when Collector destroyed, it may lost some pending messages in the queue without a `shutdown` or `flush`.

What's your opinion?

**Comment by codefromthecrypt** [comment]
in a lot of zipkin tracers, there's a way to close the async reporter
(collector here I think). This usually gives some try at finishing
in-flight spans, so blocks a little. It isn't usual for the tracer to
self-register a shutdown hook on process exit. This is a deployment choice
that library users could do on their own.
