### ISSUE TITLE
License

### ISSUE THREAD

**Issue by nicksbyman** [flier/zipkin-cpp#7]
Hi, is it possible to add a license to the root page of this repository, so we can use it in production?

**Comment by flier** [comment]
sure, I have added a [MIT license](https://github.com/flier/zipkin-cpp/blob/master/LICENSE) base on `opentracing` project.

**Comment by codefromthecrypt** [comment]
PS all of zipkin is apache (not to do any debates) and also some other OpenTracing things are also apache. food for thought.

**Comment by flier** [comment]
ok, change to use Apache license :)
