### ISSUE TITLE
Checking out proper release tag for gmock

### ISSUE THREAD

**Issue by nicksbyman** [flier/zipkin-cpp#8]
Hi, 

I get a compilation error because it looks like the "GMOCK_VER" variable for checking out the proper release tag of gmock isn't set in the build process. I get this error:

  1 Cloning into 'gmock'...
  2 fatal: invalid reference: release-
  3 CMake Error at /home/nick/mm/zipkin-cpp/gmock-prefix/tmp/gmock-gitclone.cmake:75 (message):
  4   Failed to checkout tag: 'release-'

Any ideas? 

To clarify, this error occurs at the "make" step at the top level directory of zipkin-cpp

**Comment by flier** [comment]
Thanks, changed to use gmock release package instead of git.

**Comment by nicksbyman** [comment]
Cheers that did the trick.
